#!/bin/sh
# SPDX-License-Identifier: GPL-2.0

UTS_MACHINE="aarch64"
CC_VERSION="clang version 22.1.0 (Nacho Neko)"
LD_VERSION="LLD 22.1.0-Zako-Neko-北北 (compatible with GNU linkers)"

LINUX_COMPILE_BY="root"
LINUX_COMPILE_HOST="Murasame"

cat <<EOF
#define UTS_MACHINE                "${UTS_MACHINE}"
#define LINUX_COMPILE_BY        "${LINUX_COMPILE_BY}"
#define LINUX_COMPILE_HOST        "${LINUX_COMPILE_HOST}"
#define LINUX_COMPILER                "${CC_VERSION}, ${LD_VERSION}"
EOF